# Generated by Django 5.1 on 2024-09-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='smtp_password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe SMTP '),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='smtp_port',
            field=models.IntegerField(verbose_name='Port SMTP '),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='smtp_server',
            field=models.CharField(max_length=50, verbose_name='Server SMTP '),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='smtp_username',
            field=models.CharField(max_length=50, verbose_name="Nom d'utilisateur SMTP "),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='appsettingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
    ]
