# Generated by Django 5.1 on 2024-09-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_absencemodel_student_id_and_more'),
        ('setting', '0002_alter_appsettingmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettingmodel',
            name='school_id',
        ),
        migrations.AddField(
            model_name='appsettingmodel',
            name='school',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='app_setting_school_ids', to='school.schoolmodel', verbose_name='Ecole'),
            preserve_default=False,
        ),
    ]
