# Generated by Django 5.1 on 2024-09-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_absencemodel_student_id_and_more'),
        ('user', '0003_adressmodel_student_id_adressmodel_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressmodel',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='adressmodel',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='roleusermodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='adressmodel',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress_student_ids', to='school.studentmodel'),
        ),
        migrations.AddField(
            model_name='adressmodel',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress_teacher_ids', to='school.teachermodel'),
        ),
        migrations.AddField(
            model_name='roleusermodel',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='role_user_user_ids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school_ids', to='school.schoolmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student_ids', to='school.studentmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher_ids', to='school.teachermodel'),
        ),
    ]
