# Generated by Django 5.1 on 2024-09-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_adressmodel_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleusermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AdressModel',
        ),
    ]
