# Generated by Django 5.1 on 2024-09-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_appsettingmodel_remove_absencemodel_student_and_more'),
        ('user', '0005_remove_roleusermodel_user_remove_usermodel_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.roleusermodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolmodel'),
        ),
    ]
