# Generated by Django 5.1 on 2024-09-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_appsettingmodel_remove_absencemodel_student_and_more'),
        ('user', '0006_usermodel_role_usermodel_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleusermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='roleusermodel',
            name='role',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name="Rôle de l'utilisateur "),
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ManyToManyField(to='user.roleusermodel'),
        ),
    ]
