# Generated by Django 5.1 on 2024-09-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='adress_id',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='adress_id',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='absencemodel',
            name='absence_date',
            field=models.DateField(verbose_name="Date de l'absence "),
        ),
        migrations.AlterField(
            model_name='absencemodel',
            name='absence_number',
            field=models.IntegerField(verbose_name="Nombre d'absence "),
        ),
        migrations.AlterField(
            model_name='absencemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='absencemodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='absencemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Nom '),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='url_logo',
            field=models.CharField(max_length=50, verbose_name='Lien du logo '),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='expiration_date',
            field=models.DateField(verbose_name="Date d'expiration "),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='issue_date',
            field=models.DateField(verbose_name="Date d'issue "),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Référence '),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='studentcardsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actif '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birthday',
            field=models.DateField(verbose_name='Date de naissance '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nom '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='H', max_length=1, verbose_name='Genre '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Prénoms '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='matricule',
            field=models.CharField(max_length=50, verbose_name='Matricule '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Téléphone '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number_father',
            field=models.CharField(max_length=15, verbose_name='Téléphone du père '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='url_picture',
            field=models.CharField(max_length=255, verbose_name="Lien de l'image "),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actif '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='birthday',
            field=models.DateField(verbose_name='Date de naissance '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nom '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='H', max_length=1, verbose_name='Genre '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Prénoms '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Téléphone '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='speciality',
            field=models.CharField(max_length=50, verbose_name='Spécialité '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'édition "),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='url_picture',
            field=models.CharField(max_length=255, verbose_name="Lien de l'image "),
        ),
    ]
