# Generated by Django 5.1 on 2024-09-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_studentmodel_adress_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencemodel',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentcardsmodel',
            name='student_id',
        ),
        migrations.AddField(
            model_name='absencemodel',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='absence_student_ids', to='school.studentmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcardsmodel',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_cards_student_ids', to='school.studentmodel'),
            preserve_default=False,
        ),
    ]
