# Generated by Django 5.1 on 2024-09-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_absencemodel_student_id_and_more'),
        ('user', '0005_remove_roleusermodel_user_remove_usermodel_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('smtp_server', models.CharField(max_length=50, verbose_name='Server SMTP ')),
                ('smtp_port', models.IntegerField(verbose_name='Port SMTP ')),
                ('smtp_username', models.CharField(max_length=50, verbose_name="Nom d'utilisateur SMTP ")),
                ('smtp_password', models.CharField(max_length=128, verbose_name='Mot de passe SMTP ')),
            ],
            options={
                'verbose_name': 'Paramètre appli',
                'verbose_name_plural': 'Paramètre appli',
            },
        ),
        migrations.RemoveField(
            model_name='absencemodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentcardsmodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
        migrations.AddField(
            model_name='schoolmodel',
            name='app_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_app_settings_id', to='school.appsettingmodel'),
        ),
        migrations.DeleteModel(
            name='AbsenceModel',
        ),
        migrations.DeleteModel(
            name='StudentCardsModel',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
